export const products = [
  {
    id: 1,
    name: "【新品上市】以愛織夢─靜思閱讀書軒的美與善與智慧之光",
    price: "HK$420",
    specialPrice: "HK$336",
    image: "/images/books/001.png",
    category: "書籍",
  },
  {
    id: 2,
    name: "【熱銷推薦】靜思人文─心靈的滋養與生命的深層啟迪",
    price: "HK$378",
    specialPrice: "HK$302",
    image: "/images/books/002.png",
    category: "書籍",
  },
  {
    id: 3,
    name: "【限量發售】靜思茶道精選禮盒─傳統與自然的完美結合",
    price: "HK$450",
    specialPrice: "HK$360",
    image: "/images/grocery/001.png",
    category: "百貨",
  },
  {
    id: 4,
    name: "【經典收藏】靜思詩詞全集─文化遺產的詩意傳承",
    price: "HK$420",
    specialPrice: "HK$336",
    image: "/images/books/003.png",
    category: "書籍",
  },
  {
    id: 5,
    name: "【自然養生】靜思草本飲品─健康與自然的和諧享受",
    price: "HK$378",
    specialPrice: "HK$302",
    image: "/images/grocery/002.png",
    category: "百貨",
  },
  {
    id: 6,
    name: "【智慧之書】靜思哲學導讀─心靈覺醒的深度探索",
    price: "HK$420",
    specialPrice: "HK$336",
    image: "/images/books/004.png",
    category: "書籍",
  },
  {
    id: 7,
    name: "【手工珍品】靜思陶瓷杯組",
    price: "HK$320",
    specialPrice: "HK$256",
    image: "/images/grocery/003.png",
    category: "百貨",
  },
  {
    id: 8,
    name: "【心靈旅程】靜思旅行筆記與圖畫",
    price: "HK$378",
    specialPrice: "HK$302",
    image: "/images/books/001.png",
    category: "書籍",
  },
  {
    id: 9,
    name: "【特產禮品】靜思海鹽與手工包裝",
    price: "HK$250",
    specialPrice: "HK$200",
    image: "/images/grocery/004.png",
    category: "百貨",
  },
  {
    id: 10,
    name: "【文化瑰寶】靜思繪本故事集",
    price: "HK$420",
    specialPrice: "HK$336",
    image: "/images/books/002.png",
    category: "書籍",
  },
  {
    id: 11,
    name: "【健康選擇】靜思蜂蜜罐",
    price: "HK$280",
    specialPrice: "HK$224",
    image: "/images/grocery/001.png",
    category: "百貨",
  },
  {
    id: 12,
    name: "【啟迪讀本】靜思自然科學導論",
    price: "HK$378",
    specialPrice: "HK$302",
    image: "/images/books/003.png",
    category: "書籍",
  },
  {
    id: 13,
    name: "【純手工】靜思手工皂禮盒",
    price: "HK$220",
    specialPrice: "HK$176",
    image: "/images/grocery/002.png",
    category: "百貨",
  },
  {
    id: 14,
    name: "【靜思經典】心靈詩選集",
    price: "HK$420",
    specialPrice: "HK$336",
    image: "/images/books/004.png",
    category: "書籍",
  },
  {
    id: 15,
    name: "【自然滋補】靜思草藥禮包",
    price: "HK$300",
    specialPrice: "HK$240",
    image: "/images/grocery/003.png",
    category: "百貨",
  },
  {
    id: 16,
    name: "【智慧導引】靜思哲思錄",
    price: "HK$378",
    specialPrice: "HK$302",
    image: "/images/books/001.png",
    category: "書籍",
  },
  {
    id: 17,
    name: "【限時優惠】靜思茶葉罐",
    price: "HK$350",
    specialPrice: "HK$280",
    image: "/images/grocery/004.png",
    category: "百貨",
  },
  {
    id: 18,
    name: "【人文之旅】靜思旅行日記",
    price: "HK$420",
    specialPrice: "HK$336",
    image: "/images/books/002.png",
    category: "書籍",
  },
  {
    id: 19,
    name: "【健康禮品】靜思養生套裝",
    price: "HK$400",
    specialPrice: "HK$320",
    image: "/images/grocery/001.png",
    category: "百貨",
  },
  {
    id: 20,
    name: "【靜思珍藏】自然文學",
    price: "HK$378",
    specialPrice: "HK$302",
    image: "/images/books/003.png",
    category: "書籍",
  },
];
